- hosts: all
  become: True
  tasks:
    - name: nginx
      command: amazon-linux-extras enable nginx1
      register: result

    - name: nginx
      yum:
        name: nginx
        state: present
      when: result is success

    - name: Start nginx 
      service:
        name: nginx
        state: started
        enabled: True

    - name: website
      copy:
        src: index.html
        dest: /var/www/html/
