- name: Deployer infrastructure 3-tier
  hosts: all
  become: yes
  tasks:

    - name: Installation des paquets de base
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - wget
        - vim

- name: Déployer nginx sur Web
  hosts: web
  become: yes
  tasks:
    - name: nginx
      command: amazon-linux-extras enable nginx1
      
    - name: Installer nginx
      yum:
        name: nginx
        state: present

    - name: Démarrer nginx
      service:
        name: nginx
        state: started
        enabled: true
        
    - name: website
      copy:
        src: index.html
        dest: /var/www/html/   

- name: Déployer app "htop" sur App
  hosts: app
  become: yes
  tasks:
    - name: Installer htop
      yum:
        name: htop
        state: present

- name: Déployer MySQL sur DB
  hosts: db
  become: yes
  tasks:
    - name: Installer mysql-server
      yum:
        name: mysql
        state: present

    - name: Démarrer le service mysql
      service:
        name: mysqld
        state: started
        enabled: true
